uchikoshi-fes/uchikoshi-fes.jp-2022

.gitignore
=> .textlintcache を gitignore に追加

.vscode/extensions.json, .vscode/settings.json
- [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) と [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) を導入するのを推奨
- タブサイズを 2 に設定
- デフォルトフォーマッターを Prettier に
- 保存時自動フォーマット
- 保存時自動リント修正
=> VSCode の設定を追加

.github/workflows/on_push.yml, pages/index.jsx
=> Actions で lint が失敗したときに Discord に通知するように

DEVELOP.md, README.md
=> 「かた」としての「方」を非推奨に

.github/ISSUE_TEMPLATE/0_bug_report.yml, .github/ISSUE_TEMPLATE/1_typo.yml, .github/ISSUE_TEMPLATE/2_improvement_suggestions.yml, .github/ISSUE_TEMPLATE/3_feature_request.yml, .github/ISSUE_TEMPLATE/4_for_develop.yml, .github/ISSUE_TEMPLATE/5_question.yml, .github/ISSUE_TEMPLATE/6_others.yml
close #22 
issue フォームを作成
- バグ報告
- タイポ報告
- 改善提案
- 新機能リクエスト
- 開発環境への提案
- 質問
- その他
- bug
- typo
- improvement
- enhancement
- for develop
- Q&A
- Needs Triage
- priority: HIGH
=> Issue フォーム導入

.github/workflows/on_push.yml
=> Actions の timeout 時間制限を削除

.github/workflows/license-checker.yml
close #35
- [NPM License Checker](https://www.npmjs.com/package/license-checker) で GPL系ライセンスの有無を確認する GitHub Actions を作成
=> license-checker の GitHub Actions を追加

package.json, pnpm-lock.yaml
fix #40 
- husky install がコード 127 を返したときに 0 を返すよう
- npm-run-all が devDependencies になってた問題を修整
=> production 環境でビルド時にエラーが出る問題の修正

.github/workflows/fix_branch.yml
=> PR 先ブランチ修正アクション

.github/CODEOWNERS
=> コードオーナーを指定

.github/workflows/fix-branch.yml
=> Fix branch アクションを修整

.github/workflows/auto-pr.yml, .github/workflows/fix-branch.yml, .github/workflows/license-checker.yml, .github/workflows/maintain-quality.yml
close #83 
```yaml
runs-on: ubuntu-20.04
```
=> GitHub Actions を実行する Ubuntu のバージョンを指定

__tests__/countdown.test.jsx, components/countdown.jsx
=> カウントダウンの微修正

.github/workflows/maintain-quality.yml
=> Actions を実行する Ubuntu のバージョンを指定

.github/workflows/close-issues.yml
=> Issues を閉じるアクションを追加

components/base/link.jsx, components/external-link.jsx, components/layout/footer.jsx, components/layout/header.jsx
=> a タグのリファクタリング

.github/workflows/close-issues.yml
close #87 
行末に番号が存在する場合も動作するように修正。
=> Close issues アクションを修正

.github/workflows/close-issues.yml, .github/workflows/fix-branch.yml
=> リポジトリを跨ぐアクションが動くように修正

.github/workflows/add-to-project.yml, .github/workflows/auto-pr.yml
=> Issue, PR をプロジェクトに追加するアクション

.github/workflows/add-to-project.yml, .github/workflows/auto-pr.yml, .github/workflows/close-issues.yml, .github/workflows/fix-branch.yml, .github/workflows/license-checker.yml, .github/workflows/maintain-quality.yml
=> permissions フィールドを Actions に追加

.github/workflows/maintain-quality.yml
=> 外部からのPRでも動くように修正

.editorconfig, .vscode/extensions.json, .vscode/settings.json
=> EditorConfig を追加

package.json, pages/_app.jsx, pnpm-lock.yaml
close #130 
参考: https://fontawesome.com/docs/web/use-with/react/use-with
=> Font Awesome 導入

.github/workflows/add-to-project.yml, .github/workflows/auto-pr.yml
close #132
一旦、Auto PR では実行しないようにします。
=> Add to project 修正

package.json
=> pnpm を v7.4.0 に更新

.husky/post-index-change
=> node_modules を Git と同期させる Git Hook を追加

.husky/post-checkout
=> ブランチ切り替え時に issue 情報を表示する Git Hook を追加

next.config.js, package.json, pnpm-lock.yaml
=> next-compose-plugins 追加

.husky/post-checkout, .husky/post-index-change
=> githooks 修整

__tests__/countdown.test.jsx, components/countdown.jsx, components/countdown.module.scss
=> カウントダウンを完成させる

__tests__/layout.test.jsx, components/layout/menu.jsx, pages/articles/index.jsx, pages/articles/index.module.scss, pages/articles/sample.mdx, pages/contact.jsx, pages/contact.module.scss, pages/events/index.jsx, pages/events/index.module.scss, pages/licenses.jsx, pages/licenses.module.scss, pages/map/index.jsx, pages/map/index.module.scss, pages/orgs/index.jsx, pages/orgs/index.module.scss, pages/privacy.jsx, pages/privacy.module.scss, pages/sponsors.jsx, pages/sponsors.module.scss
=> とりあえず仮でページを整理

DEVELOP.md, README.md
=> .md ファイル内のリンクを、正しく遷移しないケースがあるため修正

pages/orgs/index.jsx
=> 団体一覧ページ 画像サイズ指定

components/base/image.jsx
close #255 
https://feature--255-fix-relative-pa.mogyuchi-fes.pages.dev/
=> 画像相対パス指定対応

.gitattributes
=> CRLF が混入しないようにする

package.json, pnpm-lock.yaml
#205 で使うもの、先に入れています（コンフリクト発生し続けるのめんどいので）
=> 必要になりそうなパッケージをとりあえず追加

.textlintrc.json, components/article-container.module.scss, pages/articles/index.module.scss, pages/articles/interview-affairs.mdx, pages/articles/interview-decoration.mdx, pages/articles/interview-deputy.mdx, pages/articles/interview-info.mdx, pages/articles/interview-materials.mdx, pages/articles/interview-orgs.mdx, pages/articles/interview-sports.mdx, pages/articles/interview-stand.mdx, pages/articles/interview-student-council.mdx
邪魔な textlint のルールはどうせ今後も邪魔になるだろうし消しておいた
=> 記事タイトルの改行をいい感じに

components/base/image.jsx, jsconfig.json, pages/events.jsx, pages/index.jsx
#277 
https://feature--277-apply-revving.mogyuchi-fes.pages.dev/
=> Revving 適用

pages/events.jsx, pages/events.module.scss
=> イベントページ レイアウト修整

components/top/access.jsx
https://37a56ce9.mogyuchi-fes.pages.dev/
=> 現在地からのルート URL是正
